apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: golocal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: muhammadmaaz101/golocal-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://maazawan100:maazawan2004@cluster0.g4ozi.mongodb.net/?retryWrites=true&w=majority"