apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: golocal
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000  # Change this to a value in the valid range
  type: NodePort
