name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    env:
      DOCKER_HUB_USER: muhammadmaaz101

    steps:
      # Cleanup previous run artifacts
      - name: Cleanup workspace
        shell: bash
        run: |
          echo "Cleaning up previous run..."
          sudo chmod -R 777 "$RUNNER_TEMP" || true
          rm -rf "$RUNNER_TEMP/_temp" || true
          docker system prune -f || true
          echo "Cleanup completed"

      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: true
          fetch-depth: 0

      # Set up Minikube Docker environment
      - name: Configure Docker with Minikube
        shell: bash
        run: |
          echo "Current Docker environment:"
          docker info
          
          echo "Setting up Minikube docker-env..."
          eval $(minikube -p minikube docker-env)
          
          echo "Updated Docker environment:"
          docker info
          echo "Minikube cluster status:"
          minikube status

      # Build Docker images
      - name: Build backend image
        run: docker build -t $DOCKER_HUB_USER/golocal-backend ./app/server

      - name: Build frontend image
        run: docker build -t $DOCKER_HUB_USER/golocal-frontend ./app/client

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push images to Docker Hub
      - name: Push backend image
        run: docker push $DOCKER_HUB_USER/golocal-backend

      - name: Push frontend image
        run: docker push $DOCKER_HUB_USER/golocal-frontend

      # Deploy to Minikube
      - name: Create namespace if not exists
        run: kubectl create namespace golocal --dry-run=client -o yaml | kubectl apply -f -
      
      - name: Deploy to Minikube
        run: |
          echo "Applying Kubernetes manifests..."
          kubectl apply -f app/deployment/backend-deployment.yaml
          kubectl apply -f app/deployment/backend-service.yaml
          kubectl apply -f app/deployment/frontend-deployment.yaml
          kubectl apply -f app/deployment/frontend-service.yaml
          
          echo "Deployment status:"
          kubectl get pods -o wide
          kubectl get services

      # Post-deployment verification
      - name: Verify deployment
        shell: bash
        run: |
          echo "Cluster information:"
          kubectl cluster-info
          
          echo "Application URLs:"
          minikube service list