name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      # Checkout with newer action
      - name: Checkout code
        uses: actions/checkout@v4

      # Configure Docker to use Minikube
      - name: Set up Docker to use Minikube's environment
        shell: bash
        run: |
          echo "Configuring Docker to use Minikube's daemon..."
          eval $(minikube docker-env)
          sleep 5 

      # Build backend Docker image
      - name: Build backend Docker image
        run: docker build -t muhammadmaaz101/golocal-backend ./server

      # Build frontend Docker image
      - name: Build frontend Docker image
        run: docker build -t muhammadmaaz101/golocal-frontend ./client

      # Login to Docker Hub
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push backend image
      - name: Push backend image
        run: docker push muhammadmaaz101/golocal-backend

      # Push frontend image
      - name: Push frontend image
        run: docker push muhammadmaaz101/golocal-frontend

      # Deploy to Minikube
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment/backend-deployment.yaml
          kubectl apply -f deployment/backend-service.yaml
          kubectl apply -f deployment/frontend-deployment.yaml
          kubectl apply -f deployment/frontend-service.yaml